#
#    ░█████╗░██╗░░██╗░█████╗░████████╗░█████╗░░█████╗░████████╗██╗░█████╗░███╗░░██╗░██████╗
#    ██╔══██╗██║░░██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██╔════╝
#    ██║░░╚═╝███████║███████║░░░██║░░░███████║██║░░╚═╝░░░██║░░░██║██║░░██║██╔██╗██║╚█████╗░
#    ██║░░██╗██╔══██║██╔══██║░░░██║░░░██╔══██║██║░░██╗░░░██║░░░██║██║░░██║██║╚████║░╚═══██╗
#    ╚█████╔╝██║░░██║██║░░██║░░░██║░░░██║░░██║╚█████╔╝░░░██║░░░██║╚█████╔╝██║░╚███║██████╔╝
#    ░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═════╝░
#                                 Version ${project.version}

actions:
  wave:
    sender-text: ""
    receiver-text: ""
    aliases: []
    permission: ""
    permission-message: ""